# Generated by Django 6.0.4 on 2026-04-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ninos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='alergias',
            field=models.TextField(blank=True, help_text='Alergias conocidas', null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='enfermedades',
            field=models.TextField(blank=True, help_text='Antecedentes médicos o enfermedades', null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='situacion_familiar',
            field=models.TextField(blank=True, help_text='Situaciones particulares de la familia', null=True),
        ),
        migrations.CreateModel(
            name='AnotacionDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(default='Educadora', max_length=100)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='gestion_ninos.nino')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Atraso', 'Atraso'), ('Justificado', 'Justificado')], default='Presente', max_length=20)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion_ninos.nino')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('nino', 'fecha')},
            },
        ),
    ]
