# Generated by Django 6.0.4 on 2026-04-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ninos', '0002_nino_alergias_nino_enfermedades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('actividades', models.TextField(help_text='Actividades planificadas para el día')),
            ],
            options={
                'unique_together': {('curso', 'fecha')},
            },
        ),
    ]
