# Generated by Django 6.0.4 on 2026-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ninos', '0003_planificacioncurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Jardín Infantil INNOVA', max_length=200)),
                ('direccion', models.CharField(default='Av. Ricardo Lyon 1345, Providencia', max_length=300)),
                ('comuna', models.CharField(default='Providencia', max_length=100)),
                ('region', models.CharField(default='Región Metropolitana', max_length=100)),
                ('lat', models.FloatField(default=-33.4372)),
                ('lng', models.FloatField(default=-70.6506)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Perfil Institucional',
            },
        ),
        migrations.CreateModel(
            name='PersonalInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMeteorologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('precipitacion', models.FloatField(blank=True, help_text='mm de lluvia', null=True)),
                ('codigo_clima', models.IntegerField(blank=True, help_text='WMO weather code', null=True)),
                ('viento_max', models.FloatField(blank=True, help_text='km/h', null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='nino',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección del estudiante', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='numero_hermanos',
            field=models.IntegerField(blank=True, help_text='Número de hermanos', null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='quintil_rsh',
            field=models.IntegerField(blank=True, help_text='Quintil del Registro Social de Hogares (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='nino',
            name='situacion_laboral_padres',
            field=models.CharField(blank=True, choices=[('ninguno', 'Ningún apoderado con trabajo full time'), ('uno', 'Un apoderado con trabajo full time'), ('ambos', 'Ambos apoderados con trabajo full time')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RegistroCasosRespiratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField()),
                ('semana_epidemiologica', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('tipo_virus', models.CharField(default='Total respiratorios', max_length=100)),
                ('casos_confirmados', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
                'unique_together': {('semana_epidemiologica', 'anio', 'region', 'tipo_virus')},
            },
        ),
    ]
