# Generated by Django 6.0.4 on 2026-05-03 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ninos', '0005_nino_telefono_apoderado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('evaluacion', models.CharField(choices=[('Logrado', 'Logrado'), ('En proceso', 'En proceso'), ('Necesita apoyo', 'Necesita apoyo')], max_length=20)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gestion_ninos.nino')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('nino', 'fecha')},
            },
        ),
    ]
